name: KiwiField
version: 1.0.5
main: me.KiwiLetsPlay.KiwiField.KiwiField
author: KiwiLetsPlay
commands:
     m:
          description: medic
          usage: /<command>
     a:
          description: ammo
          usage: /<command>
     kclass:
          description: Start
          usage: /<command> <class>
          default: op